### ISSUE TITLE
apps with fragments not working (for me atleast)

### ISSUE THREAD

**Issue by mofrains** [dogriffiths/HeadFirstAndroid#22]
Hello, I've been trying to work through the book, and have run into an issue i can't figure out. In both chapter six and seven i simply can not seem to make the fragments work. No bugs are reported within android studio, and the apps will even run, but as soon as i click on a button, such as drinks in the starbuzz app, the app immediately crashes. I assume this is a issue with fragments.

To be sure it was not my own inexperience that caused the issue, i have even tried to copy the exact files from the github, and the exact same issue occurs. My android studio is fully updated, and i have followed all the advice i have found online, but still, same issue.

**Comment by dogriffiths** [comment]
Do you get any errors in the “Android Monitor” tab at the bottom of your screen?

**Comment by mofrains** [comment]
Yes, i get this: 
02-06 13:49:47.460 2583-2602/com.hfad.starbuzz E/EGL_emulation: tid 2602: eglSurfaceAttrib(1146): error 0x3009 (EGL_BAD_MATCH)
when i attempt to press the button using the fragment.
I should note that i have tried using the app on other devices, including my own physical one though.

**Comment by mofrains** [comment]
and this corresponding error in the "Run": 
E/EGL_emulation: tid 2307: eglSurfaceAttrib(1146): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa54c3fc0, error=EGL_BAD_MATCH

**Comment by dogriffiths** [comment]
I think that’s probably an emulator issue and I don’t *think* that would cause the app to crash. 

Is there a stack trace?

**Comment by mofrains** [comment]
i apologize if this is not what you are asking, as i am a novice, but i think this is it: 
02-06 14:04:37.499 16424-16424/com.hfad.starbuzz D/AndroidRuntime: Shutting down VM
02-06 14:04:37.500 16424-16424/com.hfad.starbuzz E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.hfad.starbuzz, PID: 16424
                                                                   android.content.ActivityNotFoundException: Unable to find explicit activity class {com.hfad.starbuzz/com.hfad.starbuzz.DrinkCategoryActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
                                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
                                                                       at android.app.Activity.startActivityForResult(Activity.java:4224)
                                                                       at android.app.Activity.startActivityForResult(Activity.java:4183)
                                                                       at android.app.Activity.startActivity(Activity.java:4507)
                                                                       at android.app.Activity.startActivity(Activity.java:4475)
                                                                       at com.hfad.starbuzz.TopLevelActivity$1.onItemClick(TopLevelActivity.java:25)
                                                                       at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                       at android.widget.AbsListView.performItemClick(AbsListView.java:1155)
                                                                       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3120)
                                                                       at android.widget.AbsListView$3.run(AbsListView.java:4035)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by dogriffiths** [comment]
Ah. That’s the thing. It looks like the might not have a reference to it in your `AndroidManifest.xml` file. This is a *really* common error. I do it myself all the time.

- Open AndroidManifest.xml
- Make sure it has an activity listed for DrinkCategoryActivity (you should be able to copy and rename the one for MainActivity)

Please let me know if this works.

DG

**Comment by mofrains** [comment]
That was it! Thank you so much for your quick response, really awesome. Sorry for taking up your time, but i really appreciate it, as i would have never found that out on my own.

**Comment by dogriffiths** [comment]
No problem. Glad you got it solved :-)
