### ISSUE TITLE
Problem in Chapter 7 with WorkoutListFragment 

### ISSUE THREAD

**Issue by arieleden** [dogriffiths/HeadFirstAndroid#27]
When I try running the app after creating the WorkoutListFragment class and adding it to the Activity_Main_XML, on my device, I get an error message and the app is terminated immediately. I have check the code, and it is correct, the same thing happens when I run it in the Emulator. I do not know what the problem is.

**Comment by dogriffiths** [comment]
Hello.

What's the error?

**Comment by arieleden** [comment]
I don't know what the error is. All I know is that the code is correct according to the book, yet when I run it the app is terminated with an error. Before I connected the list fragment code to the main activity the app was working fine, so I know that the error is in the list fragment.

**Comment by dogriffiths** [comment]
I mean what's the error message? Is a stack trace produced?

**Comment by arieleden** [comment]
I don't know how to read  the error messages, at this stage of the book this has not been explained yet. There are a couple  of lines in red but I don't know which one is the error, and none of them make any sense to me.

**Comment by dogriffiths** [comment]
Could you post the lines in red?

**Comment by arieleden** [comment]
This is the code I get when running on the Emulator:

>                                                 --------- beginning of crash
07-15 23:07:50.044 2570-2570/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.hfad.workout, PID: 2570
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hfad.workout/com.hfad.workout.MainActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class fragment
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                  Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class fragment
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378)
                                                     at android.app.Activity.setContentView(Activity.java:2145)
                                                     at com.hfad.workout.MainActivity.onCreate(MainActivity.java:11)
                                                     at android.app.Activity.performCreate(Activity.java:5990)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                  Caused by: android.app.Fragment$InstantiationException: Trying to instantiate a class com.hfad.workout.WorkoutListFragment that is not a Fragment
                                                     at android.app.Fragment.instantiate(Fragment.java:606)
                                                     at android.app.Fragment.instantiate(Fragment.java:582)
                                                     at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2108)
                                                     at android.app.Activity.onCreateView(Activity.java:5328)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378) 
                                                     at android.app.Activity.setContentView(Activity.java:2145) 
                                                     at com.hfad.workout.MainActivity.onCreate(MainActivity.java:11) 
                                                     at android.app.Activity.performCreate(Activity.java:5990) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                  Caused by: java.lang.ClassCastException
                                                     at android.app.Fragment.instantiate(Fragment.java:606) 
                                                     at android.app.Fragment.instantiate(Fragment.java:582) 
                                                     at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2108) 
                                                     at android.app.Activity.onCreateView(Activity.java:5328) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:378) 
                                                     at android.app.Activity.setContentView(Activity.java:2145) 
                                                     at com.hfad.workout.MainActivity.onCreate(MainActivity.java:11) 
                                                     at android.app.Activity.performCreate(Activity.java:5990) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by arieleden** [comment]
I don't know how mach this is relevant but when I use the designer on main activity I get a warning:   

Unknown fragments 
A <fragment> tag allows a layout file to dynamically include different layouts at runtime. At layout editing time the specific layout to be used is not known. You can choose which layout you would like previewed while editing the layout.
- <fragment com.hfad.workout.WorkoutListFragment ...> (Use @layout/simple_list_item_1, Pick Layout...)
- <fragment com.hfad.workout.WorkDetailFragment ...> (Use @layout/fragment_work_detail, Pick Layout...)

**Comment by dogriffiths** [comment]
It appears to think WorkoutListFragment is not a correct fragment. For WorkoutListFragment, what class does it extend and what are the import statements?

**Comment by arieleden** [comment]
Yes you have found the problem. Instead of importing the app.Fragment,  android studio imported the support v4 fragment. (I don't know what that dose). when I deleted it the program worked fine. Thanks. 

I will take the opportunity to ask another question. The list itself looks very dull, how can I make it look better, change the fonts, the color and the size?
